### PR TITLE
AB#163 - Update Project Documentation

### PR DESCRIPTION
**Pull request by StuckiSimon**

### CODE REVIEW

**Comment by michaelschufi** [comment]
Could you export the image as an SVG? I think that will be better for the PDF export.

**Comment by sir-marc** [comment]
> Could you export the image as an SVG? I think that will be better for the PDF export.

It is most likely the most efficient if everyone contributes their suggestions directly oneself.

**Comment by michaelschufi** [comment]
Fair, but I was on mobile and I don't think I have draw.io installed anyway ^^

**Comment by sir-marc** [comment]
> Fair, but I was on mobile and I don't think I have draw.io installed anyway ^^

Luckily this is a web application :D

**Review by michaelschufi — COMMENTED** [review]
Looks good to me.
Should we include a rendered PDF?

**Review by michaelschufi — APPROVED** [review]

**Comment by StuckiSimon** [comment]
> Should we include a rendered PDF?

Fine for me, are we already ready for merge?

**Review by mailaenderli — APPROVED** [review]

**Pull request merged**
