### PR TITLE
Fachartikel

### PR DESCRIPTION
**Pull request by ferinator**
Draft mit grundstruktur und kommentaren.

### CODE REVIEW

**Comment by sir-marc** [comment]
Why combine changes in the app with changes in the docs?
Other stuff:
- If you install a npm package, the lock file also get updated. You need to commit and push that, too. (this is the reason the build pipeline fails.)
- Why did you switch to word instead of latex?
- Is it necessary to bring in bootstrap? Wouldnt it be possible for us to style those few visual components by ourselves, so our app looks a bit different then every other 0815 website?

**Comment by michaelschufi** [comment]
I agree with @sir-marc. Please use latex. And why do we have code changes in a Fachartikel PR?

**Comment by sir-marc** [comment]
@michaelschufi I saw he might setup this branch on top of his other branch 'enhanced-help-dialog' which contains those changes.
@ferinator Please create another branch based on the current master do the Fachartikel changes there (and in the latex file)

**Comment by ferinator** [comment]
> Why combine changes in the app with changes in the docs?
> Other stuff:
> 
> * If you install a npm package, the lock file also get updated. You need to commit and push that, too. (this is the reason the build pipeline fails.)
> * Why did you switch to word instead of latex?
> * Is it necessary to bring in bootstrap? Wouldnt it be possible for us to style those few visual components by ourselves, so our app looks a bit different then every other 0815 website?

1. I used word in case we need to share it with the teacher, because i think she will want to write comments directly in it. But it is not problem to change it into latex

2. I guess we dont need bootstrap, i was just trying out some front-end stuff, i will create a new branch and remove it

**Pull request closed without merging**
