### PR TITLE
added prototype of help dialog

### PR DESCRIPTION
**Pull request by ferinator**

### CODE REVIEW

**Review by StuckiSimon — COMMENTED** [review]
Cool work 👍 

Just some hints regarding git branching: we usually use `61-help-dialog` for naming the branch (instead of `helpDialog`). But let's keep the branch name for this PR I suggest?

Have you checked your IDE settings? It looks as if you don't have prettier / eslint setup.
Contact us in Slack if you have any questions - atm we can provide info regarding the setup in VSC as well as IntelliJ.

**Comment by michaelschufi** [comment]
I have merged the master into it and resolved the conflicts. I also checked the files with prettier and fixed it, as it was only minor formatting. @flipmess told me he and feri are going to finish it.

**Comment by StuckiSimon** [comment]
Is there any way to close the help dialog except reloading the page? 😇

**Comment by flipmess** [comment]
xD pressing the button again, if it's not covered by the dialog <o>

**Pull request closed without merging**
